### ISSUE TITLE
Does not work in C++ peek windows

### ISSUE THREAD

**Issue by Iizuki** [fingeg/DoxygenComments#6]
Steps to reproduce:

1. Select some function that's defined elsewhere.
2. Hit _Alt + F12_ to _Peek Definition_.
3. Try to create a documentation block for the function in the opened peek window.

In the peek window only `/**/` is inserted.
`*  ` gets inserted in the function call site (ruining it).

**Comment by fingeg** [comment]
Sorry for not responding to this issue, but I am not sure how to fix it and the problem was to concrete to be my top priority.
If someone wants to try, feel free to contribute.

The concrete problem:
`DTE.ActiveDocument` returns the overall document, not the peek window. This means everything that is inserted using this document gets inserted at the place of the cursor in the top document instead of the peek window. 
But `IWpfTextView` returns the peek window, that's why the `/**/` is even recognized and triggers the auto complete.

Idea for an fixing attempt;
Find a way how the peek window counts as `ActiveDocument` or use the `IWpfTextView` buffer to edit everything, but this would mean a lot of work.

Maybe this inspires somebody to fix this issue.

**Comment by fingeg** [comment]
Fixed in version 2.0.3 with the Visual Studio 2022 support
